name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --no-codesign

      - name: Create IPA Package (.ipa)
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r QuetCanCuoc_iOS.ipa Payload

      - name: Create Release and Upload iOS IPA File
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.0.7
          name: App Quét Căn Cước v2.0.7
          files: QuetCanCuoc_iOS.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
